import Footer from "./components/footer";
import Navigation from "./components/navigation";
import "./globals.css";
export const metadata = {
  title: "Sole Labs",
  description: "Generated by Next.js",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F8FAFC]">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
