import Footer from "./components/footer";
import Navigation from "./components/navigation";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-24 my-4">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
